### ISSUE TITLE
Parallelisation 

### ISSUE THREAD

**Issue by sirinath** [xymostech/XymosTeX#1]
Please parallelised as much as possible to utilise all cores.

**Comment by xymostech** [comment]
Hi @sirinath. This repo is mostly for me to learn how TeX works for now, and isn't yet a complete implementation so I'm going to close this since adding parallelization isn't relevant to the state of the repo yet. I'm actually going to turn off issues for now but I'll open up discussions if you want to discuss this sort of thing there (or probably more relevant, the state of parallelization in TeX implementations as a whole).
